### ISSUE TITLE
Error when importing large CSV:  "ValueError Row ID too high"

### ISSUE THREAD

**Issue by Taytay** [gristlabs/grist-desktop#57]
When I tried to import my large CSV file, I got this error: "ValueError Row ID too high"

Does Grist-core have any imposed limits on file size (CSV or otherwise)? This is a 70MB file, with 4 columns, and about 1.7M rows. There is no explicit ID column in this file. I haven't examined the code to try to debug it.

**Comment by paulfitz** [comment]
I do see code to issue such an error here:
https://github.com/gristlabs/grist-core/blob/8990cd2f9bfa1815f42b7a36c9e15dad63fd0462/sandbox/grist/useractions.py#L415-L416
It was added here:
https://github.com/gristlabs/grist-core/commit/0de0cb0f4a667031bf8934fdbdee887297159d53
It doesn't really make sense as a hard-coded limit.

**Comment by Taytay** [comment]
Thanks @paulfitz! Yes, it does look like a strange hardcoding limit. I don't consider the CSV to be "that big". :)
@alexmojaki, do you know why 1M was the chosen value for a max Row ID?

**Comment by alexmojaki** [comment]
The reason to have a limit is that you could send a user action with just one row with a really high row ID and this would cause a list with that many items to be created because rows are stored densely in a list.

At the time, 1M rows was way too much for Grist to handle, not sure if that's changed.

**Comment by Taytay** [comment]
Oh dang! I didn't realize that Grist wouldn't handle such CSV. Thank you.
